config/routes.rb
Rails.application.routes.draw do
  root 'main#index'
  get 'category/:title', to: 'category#show', as: 'category'
  get '/:article_title', to: 'article#show', as: 'article'

end

app/views/common/_bottom.html.slim
.col-xs-12
  #module-image-widget-2.widget.module-image-widget
    .right-widget-title-wrap
      .next-prev-wrap
        a#prev_moduleI_55a29612e64d4.tn-ajax-prev.ajax-disable href="#"
          i.fa.fa-angle-double-left
        a#next_moduleI_55a29612e64d4.tn-ajax-next href="#"
          i.fa.fa-angle-double-right
    /! #right widget title
    #moduleI_55a29612e64d4
      .module-image-wrap.clearfix
      - @bottom.each do | article |
        .col-md-2.col-sm-3.col-xs-6
          .block-image-wrap.clearfix.tn-category-39 itemscope="" itemtype="http://schema.org/Article"
            meta content="admin" itemprop="author"
            .thumb-wrap
              a href="" rel="bookmark" title=("#{ article.article_title }")
                span.post-format
                  i.fa.fa-file-text
                img.attachment-module_square_thumb.wp-post-image alt="f2979fea97898f088c7995676633c30c" height="165" itemprop="image" src=article.article_images.first.image_url width="220"
            .block-image-content
              h3.block-title itemprop="name"
                = link_to "#{ article.article_title }", article_path( article_title: article.article_title )

app/views/common/_carusel.html.slim
#tnslider_55a2785121b4e
  .module-carousel-wrap
    .tn-flexslider.clearfix
      .tn-viewport style=("overflow: hidden; position: relative;")
        ul.tn-slides style="width: 1400%; -webkit-transition-duration: 0.4s; transition-duration: 0.4s; -webkit-transform: translate3d(0px), 0px, 0px); transform: translate3d(0px, 0px, 0px);"
          - @carusel.each do | article |
            li style=("width: 256px; float: left; display: block;")
              .block-carousel-wrap.tn-category-23 itemscope="" itemtype="http://schema.org/Article"
                .thumb-wrap
                  .thumb-overlay
                  a href=""
                    img.attachment-module_5_thumb.wp-post-image alt="" draggable="false" height="165" itemprop="image" src="#{article.article_images.first.image_url}" width="220"
                  .shares-to-social-thumb-wrap.share-invisible
                    .shares-to-social-thumb-inner
                      a.share-to-social href="http://www.facebook.com/sharer.php?u=http%3A%2F%2Fmoscow.today%2Fv-ponedelnik-budet-plyus-20-gradusov-10%2F" onclick="window.open(this.href, 'mywin',\n'left=50,top=50,width=600,height=350,toolbar=0'); return false;"
                        i.fa.fa-facebook.color-facebook
                      a.share-to-social href="https://twitter.com/intent/tweet?text=%D0%92+%D0%BF%D0%BE%D0%BD%D0%B5%D0%B4%D0%B5%D0%BB%D1%8C%D0%BD%D0%B8%D0%BA+%D0%B1%D1%83%D0%B4%D0%B5%D1%82+%D0%BF%D0%BB%D1%8E%D1%81+20+%D0%B3%D1%80%D0%B0%D0%B4%D1%83%D1%81%D0%BE%D0%B2&amp;url=http%3A%2F%2Fmoscow.today%2Fv-ponedelnik-budet-plyus-20-gradusov-10%2F&amp;via=moscow.today" onclick="window.open(this.href, 'mywin',\n'left=50,top=50,width=600,height=350,toolbar=0'); return false;"
                        i.fa.fa-twitter.color-twitter
                      a.share-to-social href="http://plus.google.com/share?url=http%3A%2F%2Fmoscow.today%2Fv-ponedelnik-budet-plyus-20-gradusov-10%2F" onclick="window.open(this.href, 'mywin',\n'left=50,top=50,width=600,height=350,toolbar=0'); return false;"
                        i.fa.fa-google-plus.color-google
                  .block-carousel-content
                    .meta-thumb-wrap
                      .meta-thumb-element.meta-thumb-views
                        i.fa.fa-share
                        span 10 views
                    / # meta thumb wrap
                    h3.block-title itemprop="name"
                      = link_to article.article_title, article_path( article_title: article.article_title )
                    .block1-meta-tag
                      ul.post-categories
                        li
                          a href="#" title="" = Category.all.sample.page_title
                      ul.post-meta
                        li.date-post-meta
                          span /
                          time datetime="2015-05-24T20:15:06+00:00" itemprop="dateCreated"  = article.created_at.to_date
                      meta content="UserComments:0" itemprop="interactionCount"
          end

app/views/common/_footer.html.slim
.tn-container
  .row.footer-sidebar-wrap.clearfix
    .footer-sidebar.widget-area.col-sm-4.col-xs-12 role="complementary"
      aside#tn_about_widget-3.footer-widget.widget.about-widget
        .widget-title
          h3 О нас
        h3.about-widget-name Moscow.Today
        /! #title
        .about-widget-content
          p.about-widget-text "Moscow.Today 2015 © Все права защищены. Мнение авторов может не совпадать с позицией редакции. При полном или частичном использовании материалов ссылка на сайт Moscow.Today обязательна. "
        /! about-content
    .footer-sidebar.widget-area.col-sm-4.col-xs-12 role="complementary"
      aside#module-post-widget-3.footer-widget.widget.module-post-widget
        .widget-title
          h3 Последние новости
        .right-widget-title-wrap
        /! #right widget title
        #moduleP_55a29612f17fe
          .module-post-wrap
            ul.module-post-content
              - @footer.each do | article |
                li
                  .block6-wrap.tn-block-wrap.tn-category-39.clearfix itemscope="" itemtype="http://schema.org/Article"
                    meta content="admin" itemprop="author"
                      .thumb-wrap
                        a href="#" rel="bookmark" title=""
                          img.attachment-small_thumb.wp-post-image alt="" height="63" itemprop="image" src="#{article.article_images.first.image_url}" width="90"
                      .block6-content
                        h3.block-title itemprop="name"
                          = link_to "#{ article.article_title }", article_path( article_title: article.article_title )
                        .block6-meta
                          ul.post-categories
                            li
                              a href="#" title="" = Category.all.sample.page_title
                          ul.post-meta
                            li.date-post-meta
                              span /
                              time datetime="2015-07-12T20:25:50+00:00" itemprop="dateCreated"  = article.created_at.to_date
                          meta content="UserComments:0" itemprop="interactionCount"
          /! #module post
    .footer-sidebar.widget-area.col-sm-4.col-xs-12 role="complementary"
      aside#tag_cloud-2.footer-widget.widget.widget_tag_cloud
        .widget-title
          h3 Рубрики
        .tagcloud
          =link_to "Архитектура", category_path( title: 'architecture' )
          =link_to "Городская Инфраструктура", category_path( title: 'urban_infrastructure' )
          =link_to "Дети", category_path( title: 'children' )
          =link_to "Животные", category_path( title:'animals' )
          =link_to "Комунальное хозяйство", category_path( title: 'public_service' )
          =link_to "Криминал", category_path( title: 'criminal' )
          =link_to "Культура", category_path( title: 'culture' )
          =link_to "Метрополитен", category_path( title: 'subway' )
          =link_to "Мигранты", category_path( title: 'migrants' )
          =link_to "Недвижимость", category_path( title: 'realty' )
          =link_to "Областная инфраструктура", category_path( title: 'regional_infrastructure' )
          =link_to "Социальний транспорт", category_path( title: 'social_transport' )
          =link_to "Общество", category_path( title: 'solution' )
          =link_to "Погода", category_path( title: 'weather' )
          =link_to "Политика", category_path( title: 'politics' )
          =link_to "Праздники", category_path( title: 'selebrates' )
          =link_to "Происшествия", category_path( title: 'accident' )
          =link_to "Развлечения", category_path( title: 'funs' )
          =link_to "Тарифы", category_path( title: 'tarifs' )
          =link_to "Транспорт", category_path( title: 'transport' )
          =link_to "Экономика", category_path( title: 'economy' )
    /! #footer sidebar
  /! #tn container

app/views/common/_go_string.html.slim
.tn-container
      .module-ticker-wrap.clearfix
        .module-ticker-inner
          ul#tn-ticker-bar.js-hidden.module-sticker-inner
            - @header.each do | article |
              li.block-ticker-wrap.tn-category-24 itemscope="" itemtype="http://schema.org/Article"
                meta content="admin" itemprop="author"
                h3.block-title itemprop="name"
                  a href="#" itemprop="url" title="article.article_title"  =article.article_title
            end
            /! #module ticker

app/views/common/_header.html.slim
header.clearfix
  .tn-container.clearfix
    #main-header
      .site-logo itemscope="itemscope" itemtype="http://schema.org/Organization" role="banner"
        .logo-content-wrap
          .logo-no-image
            h1.title-logo
              a href="/" itemprop="url" moscow.today
            h3.title-tagline Новости Москвы
          /! #no image
          meta content="moscow.today" itemprop="name"
        /! #logo content wrapper
      /! #logo
      /! #header ads
    /! #main header
    nav#main-nav.clearfix itemscope="itemscope" itemtype="http://schema.org/SiteNavigationElement" role="navigation"
      #tn-main-nav-wrap.main-nav-wrap
        .tn-container
          .main-nav-inner
            .mobile-menu-nav
              a#mobile-button-nav-open.mobile-nav-button href="#"
                i.menu-button.fa.fa-th
            /! #mobile nav wrap
            #menu-main class="menu-%d0%b3%d0%bb%d0%b0%d0%b2%d0%bd%d0%be%d0%b5-%d0%bc%d0%b5%d0%bd%d1%8e-container"
              ul.menu id="menu-%d0%b3%d0%bb%d0%b0%d0%b2%d0%bd%d0%be%d0%b5-%d0%bc%d0%b5%d0%bd%d1%8e"
                li.menu-item.menu-item-type-taxonomy.menu-item-object-category.menu-item-has-children.menu-item-6568.tn-menu-category-24
                  = link_to @economy.page_title, category_path( title: "#{@economy.title}" )
                  .tn-dropdown-menu
                    .tn-sub-menu-wrap
                      ul.tn-sub-menu.clearfix
                        li.menu-item.menu-item-type-taxonomy.menu-item-object-category.menu-item-7409.tn-menu-category-31
                          = link_to @urban_infrastructure.page_title, category_path( title: "#{ @urban_infrastructure.title }" )
                        li.menu-item.menu-item-type-taxonomy.menu-item-object-category.menu-item-7360.tn-menu-category-30
                          = link_to @architecture.page_title, category_path( title: "#{ @architecture.title }" )
                        li.menu-item.menu-item-type-taxonomy.menu-item-object-category.menu-item-7776.tn-menu-category-34
                          = link_to @public_service.page_title, category_path( title: "#{ @public_service.title }" )
                        li.menu-item.menu-item-type-taxonomy.menu-item-object-category.menu-item-7905.tn-menu-category-38
                          = link_to @realty.page_title, category_path( title: "#{ @realty.title }" )
                        li.menu-item.menu-item-type-taxonomy.menu-item-object-category.menu-item-7930.tn-menu-category-39
                          = link_to @regional_infrastructure.page_title, category_path( title: "#{ @regional_infrastructure.title }" )
                  li.menu-item.menu-item-type-taxonomy.menu-item-object-category.menu-item-8403.tn-menu-category-43
                    = link_to @tarifs.page_title, category_path( title: "#{ @tarifs.title }" )
                  li.menu-item.menu-item-type-taxonomy.menu-item-object-category.menu-item-has-children.menu-item-6563.tn-menu-category-22
                    = link_to @solution.page_title, category_path( title: "#{ @solution.title }" )
                    .tn-dropdown-menu
                      .tn-sub-menu-wrap
                        ul.tn-sub-menu.clearfix
                          li.menu-item.menu-item-type-taxonomy.menu-item-object-category.menu-item-7528.tn-menu-category-32
                            = link_to @children.page_title, category_path( title: "#{ @children.title }" )
                          li.menu-item.menu-item-type-taxonomy.menu-item-object-category.menu-item-7663.tn-menu-category-33
                            = link_to @animals.page_title, category_path( title: "#{ @animals.title }" )
                          li.menu-item.menu-item-type-taxonomy.menu-item-object-category.menu-item-8166.tn-menu-category-41
                            = link_to @selebrates.page_title, category_path( title: "#{ @selebrates.title }" )
                          li.menu-item.menu-item-type-taxonomy.menu-item-object-category.menu-item-8295.tn-menu-category-42
                            = link_to @funs.page_title, category_path( title: "#{ @funs.title }" )
                  li.menu-item.menu-item-type-taxonomy.menu-item-object-category.menu-item-has-children.menu-item-6565.tn-menu-category-25
                    = link_to @accident.page_title, category_path( title: "#{ @accident.title }" )
                    .tn-dropdown-menu
                      .tn-sub-menu-wrap
                        ul.tn-sub-menu.clearfix
                          li.menu-item.menu-item-type-taxonomy.menu-item-object-category.menu-item-7811.tn-menu-category-35
                            = link_to @criminal.page_title, category_path( title: "#{ @criminal.title }" )
                          li.menu-item.menu-item-type-taxonomy.menu-item-object-category.menu-item-7880.tn-menu-category-37
                            = link_to @migrants.page_title, category_path( title: "#{ @migrants.title }" )
                  li.menu-item.menu-item-type-taxonomy.menu-item-object-category.menu-item-6561.tn-menu-category-28
                    = link_to @weather.page_title, category_path( title: "#{ @weather.title }" )
                  li.menu-item.menu-item-type-taxonomy.menu-item-object-category.menu-item-has-children.menu-item-6567.tn-menu-category-29
                    = link_to @transport.page_title, category_path( title: "#{ @transport.title }" )
                    .tn-dropdown-menu
                      .tn-sub-menu-wrap
                        ul.tn-sub-menu.clearfix
                          li.menu-item.menu-item-type-taxonomy.menu-item-object-category.menu-item-7852.tn-menu-category-36
                            = link_to @subway.page_title, category_path( title: "#{ @subway.title }" )
                          li.menu-item.menu-item-type-taxonomy.menu-item-object-category.menu-item-8081.tn-menu-category-40
                            = link_to @social_transport.page_title, category_path( title: "#{ @social_transport.title }" )
                  li.menu-item.menu-item-type-taxonomy.menu-item-object-category.menu-item-6562.tn-menu-category-26
                    = link_to @culture.page_title, category_path( title: "#{ @culture.title }" )
                  li.menu-item.menu-item-type-taxonomy.menu-item-object-category.menu-item-6564.tn-menu-category-23
                    = link_to @politics.page_title, category_path( title: "#{ @politics.title }" )
              .ajax-search-wrap
                a#ajax-form-search.ajax-search-icon href="#"
                  i.fa.fa-search
                form.ajax-form action="/" method="get" role="search"
                  fieldset
                    input#search-form-text.field autocomplete="off" name="s" placeholder="Поиск..." type="text" value=""
                  #ajax-search-result
              /! #ajax search
            /! #main nav inner
          /! #tn container
        /! #main nav wrap
      /! # main nav
    .tn-container
      .module-ticker-wrap.clearfix
        .module-ticker-inner
          ul#tn-ticker-bar.js-hidden.module-sticker-inner
            - @header.each do | article |
              li.block-ticker-wrap.tn-category-24 itemscope="" itemtype="http://schema.org/Article"
                meta content="admin" itemprop="author"
                h3.block-title itemprop="name"
                  = link_to article.article_title, article_path( article_title: article.article_title )
            end
            /! #module ticker

app/views/common/_header_category.html.slim
header.clearfix
  .tn-container.clearfix
    #main-header
      .site-logo itemscope="itemscope" itemtype="http://schema.org/Organization" role="banner"
        .logo-content-wrap
          .logo-no-image
            h1.title-logo
              a href="/" itemprop="url"  moscow.today
            h3.title-tagline Новости Москвы
          /! #no image
          meta content="moscow.today" itemprop="name"
        /! #logo content wrapper
      /! #logo
      /! #header ads
    /! #main header
  nav#main-nav.clearfix itemscope="itemscope" itemtype="http://schema.org/SiteNavigationElement" role="navigation"
    #tn-main-nav-wrap.main-nav-wrap
      .tn-container
        .main-nav-inner
          .mobile-menu-nav
            a#mobile-button-nav-open.mobile-nav-button href="#"
              i.menu-button.fa.fa-th
          /! #mobile nav wrap
          #menu-main class="menu-%d0%b3%d0%bb%d0%b0%d0%b2%d0%bd%d0%be%d0%b5-%d0%bc%d0%b5%d0%bd%d1%8e-container"
            ul.menu id="menu-%d0%b3%d0%bb%d0%b0%d0%b2%d0%bd%d0%be%d0%b5-%d0%bc%d0%b5%d0%bd%d1%8e"
              li.menu-item.menu-item-type-taxonomy.menu-item-object-category.menu-item-has-children.menu-item-6568.tn-menu-category-24
                = link_to @economy.page_title, category_path( title: "#{@economy.title}" )
                .tn-dropdown-menu
                  .tn-sub-menu-wrap
                    ul.tn-sub-menu.clearfix
                      li.menu-item.menu-item-type-taxonomy.menu-item-object-category.menu-item-7409.tn-menu-category-31
                        = link_to @urban_infrastructure.page_title, category_path( title: "#{ @urban_infrastructure.title }" )
                      li.menu-item.menu-item-type-taxonomy.menu-item-object-category.menu-item-7360.tn-menu-category-30
                        = link_to @architecture.page_title, category_path( title: "#{ @architecture.title }" )
                      li.menu-item.menu-item-type-taxonomy.menu-item-object-category.menu-item-7776.tn-menu-category-34
                        = link_to @public_service.page_title, category_path( title: "#{ @public_service.title }" )
                      li.menu-item.menu-item-type-taxonomy.menu-item-object-category.menu-item-7905.tn-menu-category-38
                        = link_to @realty.page_title, category_path( title: "#{ @realty.title }" )
                      li.menu-item.menu-item-type-taxonomy.menu-item-object-category.menu-item-7930.tn-menu-category-39
                        = link_to @regional_infrastructure.page_title, category_path( title: "#{ @regional_infrastructure.title }" )
                li.menu-item.menu-item-type-taxonomy.menu-item-object-category.menu-item-8403.tn-menu-category-43
                  = link_to @tarifs.page_title, category_path( title: "#{ @tarifs.title }" )
                li.menu-item.menu-item-type-taxonomy.menu-item-object-category.menu-item-has-children.menu-item-6563.tn-menu-category-22
                  = link_to @solution.page_title, category_path( title: "#{ @solution.title }" )
                  .tn-dropdown-menu
                    .tn-sub-menu-wrap
                      ul.tn-sub-menu.clearfix
                        li.menu-item.menu-item-type-taxonomy.menu-item-object-category.menu-item-7528.tn-menu-category-32
                          = link_to @children.page_title, category_path( title: "#{ @children.title }" )
                        li.menu-item.menu-item-type-taxonomy.menu-item-object-category.menu-item-7663.tn-menu-category-33
                          = link_to @animals.page_title, category_path( title: "#{ @animals.title }" )
                        li.menu-item.menu-item-type-taxonomy.menu-item-object-category.menu-item-8166.tn-menu-category-41
                          = link_to @selebrates.page_title, category_path( title: "#{ @selebrates.title }" )
                        li.menu-item.menu-item-type-taxonomy.menu-item-object-category.menu-item-8295.tn-menu-category-42
                          = link_to @funs.page_title, category_path( title: "#{ @funs.title }" )
                li.menu-item.menu-item-type-taxonomy.menu-item-object-category.menu-item-has-children.menu-item-6565.tn-menu-category-25
                  = link_to @accident.page_title, category_path( title: "#{ @accident.title }" )
                  .tn-dropdown-menu
                    .tn-sub-menu-wrap
                      ul.tn-sub-menu.clearfix
                        li.menu-item.menu-item-type-taxonomy.menu-item-object-category.menu-item-7811.tn-menu-category-35
                          = link_to @criminal.page_title, category_path( title: "#{ @criminal.title }" )
                        li.menu-item.menu-item-type-taxonomy.menu-item-object-category.menu-item-7880.tn-menu-category-37
                          = link_to @migrants.page_title, category_path( title: "#{ @migrants.title }" )
                li.menu-item.menu-item-type-taxonomy.menu-item-object-category.menu-item-6561.tn-menu-category-28
                  = link_to @weather.page_title, category_path( title: "#{ @weather.title }" )
                li.menu-item.menu-item-type-taxonomy.menu-item-object-category.menu-item-has-children.menu-item-6567.tn-menu-category-29
                  = link_to @transport.page_title, category_path( title: "#{ @transport.title }" )
                  .tn-dropdown-menu
                    .tn-sub-menu-wrap
                      ul.tn-sub-menu.clearfix
                        li.menu-item.menu-item-type-taxonomy.menu-item-object-category.menu-item-7852.tn-menu-category-36
                          = link_to @subway.page_title, category_path( title: "#{ @subway.title }" )
                        li.menu-item.menu-item-type-taxonomy.menu-item-object-category.menu-item-8081.tn-menu-category-40
                          = link_to @social_transport.page_title, category_path( title: "#{ @social_transport.title }" )
                li.menu-item.menu-item-type-taxonomy.menu-item-object-category.menu-item-6562.tn-menu-category-26
                  = link_to @culture.page_title, category_path( title: "#{ @culture.title }" )
                li.menu-item.menu-item-type-taxonomy.menu-item-object-category.menu-item-6564.tn-menu-category-23
                  = link_to @politics.page_title, category_path( title: "#{ @politics.title }" )
            .ajax-search-wrap
              a#ajax-form-search.ajax-search-icon href="#"
                i.fa.fa-search
              form.ajax-form action="/" method="get" role="search"
                fieldset
                  input#search-form-text.field autocomplete="off" name="s" placeholder="Поиск..." type="text" value=""
                #ajax-search-result
            /! #ajax search
          /! #main nav inner
  /! #tn container
      /! #main nav wrap
  /! # main nav

app/views/common/_index.html.slim
#full-top.row.clearfix
  .col-xs-12
    #tn-carousel-4.widget.module-carousel-widget
      = render 'common/carusel'
      / #module carousel
    #module3-widget-2.widget.module3-widget
      = render 'common/lastnews'
    #module3-widget-3.widget.module3-widget
      = render 'common/popular'
/! #top
#full-bottom.row.clearfix
  = render 'common/bottom'
/! #bottom

app/views/common/_lastnews.html.slim
.widget-title
  h3 Последние новости
.right-widget-title-wrap
  .next-prev-wrap
    a#prev_module3_55a278513c6c7.tn-ajax-prev.ajax-disable href="#"
      i.fa.fa-angle-double-left
    a#next_module3_55a278513c6c7.tn-ajax-next href="#"
      i.fa.fa-angle-double-right
/ #right widget title
#module3_55a278513c6c7
  .module3-wrap
    .row-fluid.clearfix
      / row fluid
      - @last_news.each do | article |
        .col-sm-4.col-xs-12
          .block4-wrap.tn-block-wrap.tn-category-24.clearfix itemscope="" itemtype="http://schema.org/Article"
            meta content="admin" itemprop="author"
              .thumb-wrap
                a href="" rel="bookmark" title=article.article_title
                  span.post-format
                    i.fa.fa-file-text
                  img.attachment-module_medium_thumb.wp-post-image alt="" height="165" itemprop="image" src=article.article_images.first.image_url width="220"
                .meta-thumb-wrap
                  .meta-thumb-element.meta-thumb-views
                    i.fa.fa-share
                    span 0 view
                /! # meta thumb wrap
                .shares-to-social-thumb-wrap.share-invisible
                  .shares-to-social-thumb-inner
                    a.share-to-social href="http://www.facebook.com/sharer.php?u=http%3A%2F%2Fmoscow.today%2Fne-bylo-nikakogo-selfi-znakomye-devushki-pogibshej-v-rajone-siti-rasskazali-podrobnosti-tragedii-23%2F" onclick="window.open(this.href, 'mywin',\n'left=50,top=50,width=600,height=350,toolbar=0'); return false;"
                      i.fa.fa-facebook.color-facebook
                    a.share-to-social href="https://twitter.com/intent/tweet?text=%D0%9D%D0%B5+%D0%B1%D1%8B%D0%BB%D0%BE+%D0%BD%D0%B8%D0%BA%D0%B0%D0%BA%D0%BE%D0%B3%D0%BE+%D1%81%D0%B5%D0%BB%D1%84%D0%B8%3A+%D0%B7%D0%BD%D0%B0%D0%BA%D0%BE%D0%BC%D1%8B%D0%B5+%D0%B4%D0%B5%D0%B2%D1%83%D1%88%D0%BA%D0%B8%2C+%D0%BF%D0%BE%D0%B3%D0%B8%D0%B1%D1%88%D0%B5%D0%B9+%D0%B2+%D1%80%D0%B0%D0%B9%D0%BE%D0%BD%D0%B5+%D0%A1%D0%B8%D1%82%D0%B8%2C+%D1%80%D0%B0%D1%81%D1%81%D0%BA%D0%B0%D0%B7%D0%B0%D0%BB%D0%B8+%D0%BF%D0%BE%D0%B4%D1%80%D0%BE%D0%B1%D0%BD%D0%BE%D1%81%D1%82%D0%B8+%D1%82%D1%80%D0%B0%D0%B3%D0%B5%D0%B4%D0%B8%D0%B8&amp;url=http%3A%2F%2Fmoscow.today%2Fne-bylo-nikakogo-selfi-znakomye-devushki-pogibshej-v-rajone-siti-rasskazali-podrobnosti-tragedii-23%2F&amp;via=moscow.today" onclick="window.open(this.href, 'mywin',\n'left=50,top=50,width=600,height=350,toolbar=0'); return false;"
                      i.fa.fa-twitter.color-twitter
                    a.share-to-social href="http://plus.google.com/share?url=http%3A%2F%2Fmoscow.today%2Fne-bylo-nikakogo-selfi-znakomye-devushki-pogibshej-v-rajone-siti-rasskazali-podrobnosti-tragedii-23%2F" onclick="window.open(this.href, 'mywin',\n'left=50,top=50,width=600,height=350,toolbar=0'); return false;"
                      i.fa.fa-google-plus.color-google
              /! #thumb wrap
              .block4-content
                .block4-meta-tag
                  .block4-left-meta-tag
                    ul.post-categories
                      li
                        a href="#" title="" = Category.all.sample.page_title
                    ul.post-meta
                      li.date-post-meta
                        span /
                        time datetime="2015-07-12T17:43:58+00:00" itemprop="dateCreated"  12.07.2015
                    meta content="UserComments:0" itemprop="interactionCount" /
                  .block4-right-meta-tag
                    ul.post-meta
                      li.comment-post-meta
                        span /
                        a href=article.article_title  No Comment
                    meta content="UserComments:0" itemprop="interactionCount" /
                h3.block-title itemprop="name"
                  = link_to article.article_title, article_path( article_title: article.article_title )
    .row-fluid.clearfix
      - @last_news_small.each do | article |
        .col-sm-4.col-xs-12
          .block6-wrap.tn-block-wrap.tn-category-33.clearfix itemscope="" itemtype="http://schema.org/Article"
            meta content="admin" itemprop="author"
            .thumb-wrap
              a href="" rel="bookmark" title='article.article_title'
                img.attachment-module_medium_thumb.wp-post-image alt="" height="165" itemprop="image" src=article.article_images.first.image_url width="220"
            /! #thumb wrap
            .block6-content
              h3.block-title itemprop="name"
                = link_to article.article_title, article_path( article_title: article.article_title )
              .block6-meta
                ul.post-categories
                  li
                    a href="#" title="" = Category.all.sample.page_title
                ul.post-meta
                  li.date-post-meta
                    span /
                    time datetime="2015-07-12T17:43:58+00:00" itemprop="dateCreated"  12.07.2015
                  meta content="UserComments:0" itemprop="interactionCount" /